# Package imports
import numpy as np
from PIL import Image

# Local imports
from matplotlib import pyplot as plt
from DDPMLHC.config import *
from DDPMLHC.data_loading import NoisyGenerator

def save_to_bmap(vector, bins=BMAP_SQUARE_SIDE_LENGTH, jet_no="NONE", mu="NONE", save_path=None):
    if vector.size != bins*bins:
        raise RuntimeError(f"Vector not of size {bins}x{bins}={bins*bins}")
    if save_path is None:
        save_path = f"{CWD}/data/plots/bmaps"
    # print(vector)
    sd = np.std(vector)
    scaled_for_bmap = 255 * vector / (3 * sd)  # Scale to 3 std dev
    
    grid = scaled_for_bmap.reshape((bins, bins))  # Get grid, with scaling for bmap visualisation
    # print(grid)
    grid = np.clip(grid, 0, 255).astype(np.uint8)  # Remove OOB vals
    
    im = Image.fromarray(grid)
    filename = f"event_{int(jet_no)}_mu{int(mu)}"
    im.save(f"{save_path}/{filename}.png")

def plot_mu_comparison(tt, pile_up, use_log=False, save_path=None):
    """
    Plot grids for different mu values side by side.
    Each mu shows 4 jets arranged in a 2x2 grid.
    Generated by Claude 3.5.
    """
    # Create figure with more space
    fig = plt.figure(figsize=(16, 6))  # Increased height slightly for labels
    
    # Create gridspec to have better control over spacing
    gs = fig.add_gridspec(1, 3, wspace=0.3)
    main_axes = [fig.add_subplot(gs[0, i]) for i in range(3)]
    
    # Get mu values
    mu_values = [0, 100, 200]
    vmin, vmax = float('inf'), -float('inf')

    # Store random state
    rng_state = np.random.get_state()
    
    # First pass to get global scaling across all jets and mu values
    all_grids = []
    for mu in mu_values:
        # Reset random state to get same jets
        np.random.set_state(rng_state)
        
        mu_grids = []
        NG = NoisyGenerator(tt, pile_up, mu=mu)
        
        for _ in range(4):
            next(NG)
            grid = NG.get_grid(normalise=False)
            if use_log:
                grid = np.log1p(grid)
            vmin = min(vmin, grid.min())
            vmax = max(vmax, grid.max())
            mu_grids.append(grid)
        all_grids.append(mu_grids)
    
    # Plot each mu subplot with its 4 jets
    letters = ['(a)', '(b)', '(c)']
    for idx, (grids, mu, letter) in enumerate(zip(all_grids, mu_values, letters)):
        # Create 2x2 grid for this mu
        grid_size = grids[0].shape[0]
        combined_grid = np.zeros((grid_size * 2, grid_size * 2))
        
        # Fill the 2x2 grid
        combined_grid[:grid_size, :grid_size] = grids[0]
        combined_grid[:grid_size, grid_size:] = grids[1]
        combined_grid[grid_size:, :grid_size] = grids[2]
        combined_grid[grid_size:, grid_size:] = grids[3]

        im = main_axes[idx].imshow(combined_grid, 
                                    cmap='viridis',
                                    vmin=vmin,
                                    vmax=vmax,
                                    norm=None,  # Add this to prevent automatic normalization
                                    interpolation='nearest')
        
        # Add grid lines to separate events
        main_axes[idx].axhline(y=grid_size-0.5, color='white', linewidth=1)
        main_axes[idx].axvline(x=grid_size-0.5, color='white', linewidth=1)
        
        # Move mu label to bottom
        main_axes[idx].text(0.5, -0.1, f'{letter} $\mu = {mu}$',
                          transform=main_axes[idx].transAxes,
                          fontsize=18, ha='center')
        
        main_axes[idx].axis('off')
    
    print(f"Maximum energy in any pixel: {max([grid.max() for grids in all_grids for grid in grids]):.4f}")

    # Add colorbar with proper spacing
    cbar_ax = fig.add_axes([0.92, 0.15, 0.02, 0.7])
    cbar = fig.colorbar(im, cax=cbar_ax)
    cbar.set_label('$\ln\left(1+E/\\textrm{GeV}\\right)$' if use_log else 'Energy', fontsize=18)
    
    # Save if path provided
    if save_path:
        plt.savefig(save_path, 
                   bbox_inches='tight', 
                   dpi=300,
                   pad_inches=0.2)
        print(f"Saved figure to {save_path}")
        plt.close()
    else:
        plt.show()
